INSERT INTO station VALUES('KDHSTA001','Sungai Petani','Sungai Petani, Kedah, Malaysia Stesyen Ktm, Jln Ibrahim, 08000, Sungai Petani, Kedah','R364','KDH');
INSERT INTO station VALUES('KDHSTA002','Gurun','Kampung Pulau Chengai, 08300 Gurun Kedah, Malaysia','R364','KDH');
INSERT INTO station VALUES('KDHSTA003','Alor Star','Jalan Kolam Air, Alor Malai, 05200 Alor Setar, Kedah','R364','KDH');
INSERT INTO station VALUES('KDHSTA004','Anak Bukit','Anak Bukit, 05150 Alor Setar, Kedah','R364','KDH');
INSERT INTO station VALUES('KLSTA001','KL Sentral','Kuala Lumpur Sentral, 50470 Kuala Lumpur, Federal Territory of Kuala Lumpur','R366','KL');
INSERT INTO station VALUES('KLSTA002','Kuala Lumpur','Kuala Lumpur Railway Station, Jalan Sultan Hishamuddin, 50621 Kuala Lumpur, Malaysia','R366','KL');
INSERT INTO station VALUES('KLSTA003','Kepong Sentral','Bandar Sri Damansara, 52100 Sungai Buloh, Selangor','R366','KL');
INSERT INTO station VALUES('NSNSTA001','Gemas','Kawasan Industri Gemas, 73400 Gemas, Negeri Sembilan','R367','NSN');
INSERT INTO station VALUES('NSNSTA002','Batang Melaka','77500 Batang Melaka, Malacca','R367','NSN');
INSERT INTO station VALUES('NSNSTA003','Pulau Sebang/Tampin','78000 Alor Gajah, Malacca','R367','NSN');
INSERT INTO station VALUES('NSNSTA004','Seremban','Ktm Komuter Station, Bandar Seremban,70300 Seremban,Negeri Sembilan','R367','NSN');
INSERT INTO station VALUES('NSNSTA005','Kajang','43000 Kajang, Selangor','R367','NSN');
INSERT INTO station VALUES('NSNSTA006','Bandar Tasek Selatan','Bandar Tasek Selatan, 57100 Kuala Lumpur, Federal Territory of Kuala Lumpur','R367','NSN');
INSERT INTO station VALUES('PNGSTA001','Bukit Mertajam','2916, Jalan Padang Lalang, 14000 Bukit Mertajam, Pulau Pinang','R362','PNG');
INSERT INTO station VALUES('PNGSTA002','Butterworth','Stesen Keretapi Butterworth,Jalan Bagan Dalam,12000 Butterworth, Pulau Pinang','R362','PNG');
INSERT INTO station VALUES('PNGSTA003','Tasek Gelugor','13100 Tasek Gelugor, Penang','R362','PNG');
INSERT INTO station VALUES('PRKSTA001','Parit Bundar','Kampung Permatang Tok Mamat, 34200 Parit Buntar, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA002','Bagan Serai','34300 Bagan Serai, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA003','Taiping','Taiping Railway Station, Jalan Stesen, 34000 Taiping, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA004','Padang Rengas','Jalan Pertanian, 33700 Padang Rengas, Negeri Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA005','Kuala Kangsar','Stesen Keretapi Kuala Kangsar,Jalan Tun Razak, 33000 Kuala Kangsar, Negeri Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA006','Sungai Siput','31100 Sungai Siput, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA007','Ipoh','Stesen KTM Ipoh, 30000 Ipoh, Perak, 30100 Ipoh, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA008','Batu Gajah','Kampung Belangkor, 30200 Batu Gajah, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA009','Kampar','31900 Kampar, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA010','Sunkai','35600 Sungkai, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA011','Slim River','Kampung Manggis, 35800 Slim River, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA012','Behrang','35950 Behrang Stesen, Perak','R363','PRK');
INSERT INTO station VALUES('PRKSTA013','Tanjung Malim','Stesen KTM Tanjung Malim, 35900 Tanjung Malim, Perak, Kampung Stesen Tanjong Malim, 35900 Tanjong Malim, Perak','R363','PRK');
INSERT INTO station VALUES('SLGSTA001','Kuala Kubu Bharu','44000 Kuala Kubu Bharu, Selangor','R365','SLG');
INSERT INTO station VALUES('SLGSTA002','Batang Kali','44200 Batang Kali, Selangor','R365','SLG');
INSERT INTO station VALUES('SLGSTA003','Rawang','48000 Rawang, Selangor','R365','SLG');
INSERT INTO station VALUES('SLGSTA004','Sungai Buloh','47000 Sungai Buloh, Selangor','R365','SLG');
